GET http://localhost:3000/blog/posts HTTP/1.1

###
GET http://localhost:3000/blog/posts/62bcf8e4c37f61fd739b8ad4  HTTP/1.1

###
DELETE http://localhost:3000/blog/posts/62bcf8e4c37f61fd739b8ad4 HTTP/1.1

###
POST http://localhost:3000/blog/posts HTTP/1.1
content-type: application/json 
Date: {{$datetime iso8601}}

{
    "author": "Darlene Alderson",
    "date": "{{$datetime 'YYYY-MM-DDThh:mm:ss'}}",
    "body": "I'm sorry Elliot.",
    "replies": []
}

###
PATCH http://localhost:3000/blog/posts/62b9443ffb0a4e1798c7476f HTTP/1.1
content-type: application/json

{
    "author": "Leon", 
    "date": "{{$datetime 'YYYY-MM-DDThh:mm:ss'}}"
    
}

### Replies ###
PATCH http://localhost:3000/blog/post/replies HTTP/1.1
Content-Type: application/json

{
    
    "path": "629da8dd90329072b7ed96c0\\629db1310d0cb7470d2538f2\\629db973814ae21e7f0dc163"
}

###
POST http://localhost:3000/blog/post/replies HTTP/1.1
content-type: application/json
Date: {{$datetime iso8601}}

{
    "author": "Ruben Mora", 
    "date": "{{$datetime 'YYYY-MM-DDThh:mm:ss' }}",
    "body": "We're gonna miss ya Carlos! Have fun in Florida buddy!",
    "path": "62a5750d659f743e8aab39e1"
}

### Get a reply ###
GET http://localhost:3000/blog/post/replies HTTP/1.1
Content-Type: application/json

{
    "path": "629da8dd90329072b7ed96c0\\629db1310d0cb7470d2538f2"
}

### Delete a reply ###
DELETE  http://localhost:3000/blog/post/replies HTTP/1.1
Content-Type: application/json

{
    "path": "629da8dd90329072b7ed96c0\\629db1310d0cb7470d2538f2\\629dba356d0f98ecff8005af"
}