# Main workflow for this API Project
name: Blogger API Production Pipeline 

# Start this workflow on a dispatch event (manual).
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'info'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: false
  
# The jobs of this work flow will be the to test, build and deploy this API to 
# it's designated server. 
jobs:
  
  # Preform the Jest tests setup for this API to make sure they are all still passing 
  test: 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Run tests
        run: echo "To be tested."
    
  # Deploying and building will happen in one step since the build process produces needs to happen on the web server.
  deploy-build: 

    # Tests mus be preformed and passed before deployment.
    needs: test

    # Specificy what version of Ubuntu we're using 
    runs-on: ubuntu-latest

    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can 
      # access it
      - uses: actions/checkout@v3
      
      # Setup SSH keys to be added from Git Hub secretes to default files on 
      # runner OS. Use default files to preform rsync command to move fresly 
      # built website to webserver  
      - name: Setup SSH Keys and Known_hosts
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.DIGI_O_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      
      # Run the command set to deploy this webserver
      - name: Deploy to Digital Ocean webserver
        run: |
          echo "Directories"
          ls
          rsync -rav api bmiller@137.184.190.165:/var/www/benjmiller.dev/pprojects/apis/blogger

      # Tell the server to build the project 
      - name: Build Blogger API on Server
        run: |
          ssh 'cd /var/www/benjmiller.dev/pprojects/apis/blogger/ && nest build'
        
      # Restart the Blogger API PM2 process
      - name: Restart the Blogger API process on Server
        run: ssh 'pm2 restart \'Blogger API\''
